### ISSUE TITLE
Should I pass --no_eval for pretraining?

### ISSUE THREAD

**Issue by voidism** [oriram/spider#1]
HI!

Thanks a lot for open-sourcing the code for spider. I am trying to pretrain a spider by myself. I follow the bash command you have in README. However, in the middle of training, there is an error:

```
...
Train batch 199600, Avg. loss per last 100 batches: 0.5863998779654502, Accuracy: 77.5%
Train batch 199700, Avg. loss per last 100 batches: 0.6070431210100651, Accuracy: 75.9%
Train batch 199800, Avg. loss per last 100 batches: 0.634523368626833, Accuracy: 73.9%
Train batch 199900, Avg. loss per last 100 batches: 0.5993769405782223, Accuracy: 75.6%
Train batch 200000, Avg. loss per last 100 batches: 0.597538762241602, Accuracy: 77.4%
NLL validation ...
Traceback (most recent call last):
  File "train_dense_cmlm.py", line 1297, in <module>

  File "train_dense_cmlm.py", line 1280, in main

  File "train_dense_cmlm.py", line 337, in run_pretraining
    self._train_epoch(scheduler, epoch, train_iterator)
  File "train_dense_cmlm.py", line 731, in _train_epoch
    self.validate_and_save(epoch, self.global_step, scheduler, eval=(not args.no_eval), save=(not args.no_save))
  File "train_dense_cmlm.py", line 361, in validate_and_save
    total_loss, correct_ratio = self.validate_nll()
  File "train_dense_cmlm.py", line 400, in validate_nll
    args.dev_file, args.dev_batch_size, shuffle=False
  File "train_dense_cmlm.py", line 152, in get_data_iterator
    for pattern in path.split(","):
AttributeError: 'NoneType' object has no attribute 'split'`
```

It seems that the reason is we don't pass `args.dev_file` at all (according to README), so we cannot load it with `get_data_iterator`. Should we just pass `--no_eval` to disable evaluation when training (but you don't pass --no_eval in README)? Or do you have a dev_file we can use in pretraining (it seems not the case because it's unsupervised pretraining)?
Thanks a lot!

**Comment by oriram** [comment]
Hi Yung-Sung!
Thanks for expressing your interest in our paper :)

This is my bad, I should have added the `--no_eval` to the command in the README. You should also set `--eval_steps` in order to save checkpoints while training.
Anyway, I'll modify the README accordingly.

Sorry and good luck!

**Comment by voidism** [comment]
Hi Ori!

I see. Thanks a lot for your prompt reply:) I will set `--eval_steps` to save checkpoints. Thanks again for open-sourcing the code for this amazing paper!
