### ISSUE TITLE
question: relation with Splinter/joint reader and retriever training

### ISSUE THREAD

**Issue by PaulLerner** [oriram/spider#2]
Hi Ori,

Because both Spider and [Splinter](https://github.com/oriram/splinter) are based on recurring spans, 
I wondered if you further explored the combination of the two pre-training tasks.
For example, you could have jointly trained the encoder of the retriever and the reader, simply adding the QASS on top of the encoder for the reader (see e.g. http://arxiv.org/abs/2104.10129). Or is it something that you consider for future work?

Bests,

Paul

**Comment by oriram** [comment]
Hi Paul!

Thanks for showing interest in our papers!  
We didn't really consider the combination of Splinter and Spider into a unified pretraining.
However, it definitely sounds like a promising direction :)

Best,
Ori

**Comment by PaulLerner** [comment]
Hi Ori,

Ok thank you for your answer :)
