### ISSUE TITLE
Released checkpoints on Huggingface

### ISSUE THREAD

**Issue by memray** [oriram/spider#3]
Hi @oriram ,

I wonder if these two unsupervised spider checkpoints ([tau/spider](https://huggingface.co/tau/spider) and [NAACL2022/spider](https://huggingface.co/NAACL2022/spider)) are official? I cannot get sensible results from them. By checking the weights, it's more like that it's a randomly initialized checkpoint. Could you please take a look at it? I'm not sure if the finetuned checkpoints have the same issue.

Thanks,
Rui

**Comment by oriram** [comment]
Hi @memray,
Thanks for using our repo!

How are you trying to use Spider?

First, these two checkpoints are equivalent.
Second, unfortunately the ``DPRContextEncoder`` class (in `transformers`) can't be initiated using `AutoModel`, so you'll need to use:
```python
model = DPRContextEncoder.from_pretrained("tau/spider")
```
(an example code can be found in the model's README at https://huggingface.co/tau/spider)

Let me know if this helps.
Best,
Ori

**Comment by memray** [comment]
Hi Ori! Thanks for the speedy reply.
I was trying to evaluate the unsupervised checkpoint on QA datasets and I used `model = DPRQuestionEncoder.from_pretrained("tau/spider")`. 
Are `DPRQuestionEncoder` and `DPRContextEncoder ` functionally different? 
Are spider QE and CE two separate models? I only see "tau/spider" on Huggingface and I thought the parameters are shared. 
Do I also need to do additional pooling for the output ([CLS] embedding I think spider is using)?

Thanks!

**Comment by memray** [comment]
I believe the problem is because of a name mismatch. When I load the checkpoint via HF api, it pops this message: `Some weights of DPRQuestionEncoder were not initialized from the model checkpoint at tau/spider and are newly initialized`.

Basically the names of spider weights start with `ctx_encoder.bert_model.*` but the model's weights start with `bert_model.*`.

**Comment by oriram** [comment]
Hey Rui,
Spider's QE and CE are the same model.
However, technically you should load the model with the `DPRContextEncoder` class, *not* with `DPRQuestionEncoder`.
If you execute `DPRContextEncoder.from_pretrained("tau/spider")` you should be fine :)

**Comment by memray** [comment]
You are right! It works :D
Thank you!
