### ISSUE TITLE
Handling of data without titles

### ISSUE THREAD

**Issue by rbbby** [oriram/spider#6]
I am working with retrieval of documents that lack meaningful titles (they are ids).

With titles the model input data is as I understand it concatenated as "_title [SEP] body_".
I figure that you can supply titles as empty strings and the resulting input to the tokenizer would be "[SEP] body_".
While this likely will not have any noticeable effect on performance, it is not very elegant nor optimal.

How is data with no titles handled and are there any recommendations of how to work with it?
Thanks!

**Comment by oriram** [comment]
Hi @rbbby ,
Thanks for using our model!
In Spider's training there aren't any passages without titles (unfortunately), but I suggest you try both **with** and **without** the `[SEP]` token before the passage text (good chance performance will be pretty similar).

**Comment by rbbby** [comment]
Thanks!
