### ISSUE TITLE
Question about reproducing the results of Trivia QA

### ISSUE THREAD

**Issue by Gouzi3618** [oriram/spider#8]
Hi Ori, 

Thanks for your great work!

Currently, I find following your readme, using your released model, I can get the same NQ results as in the paper but not Trivia QA. 

The recall I got is Recall@100 0.338, which is much lower than the result in the paper. Do you have some guess which part could be wrong? Thanks a lot!

Thanks!

Best,
Gouzi

**Comment by oriram** [comment]
Hey @Gouzi3618,
Can you please share the commands you ran to reproduce the results?
Thanks!

**Comment by Gouzi3618** [comment]
Hi Ori, 

Thanks for your reply!

I first download the Wikipedia file by
python download_data.py --resource data.wikipedia_split.psgs_w100

Then I tokenize the Wiki:
python preprocess_corpus.py \
--corpus_path ./downloads/data/wikipedia_split/psgs_w100.tsv \
--output_dir ./wiki/ \
--tokenizer_name bert-base-uncased \
--num_processes 64  \

Then I download the test csv of TQA by
python download_data.py --resource data.retriever.qas.trivia-test

Then encode the Wikipedia:
python generate_dense_embeddings.py \
--encoder_model_type hf_bert \
--pretrained_model_cfg tau/spider \
--input_file "./wiki/tokenized_*.pkl" \
--output_dir ./wiki_embeddings/ \
--fp16 \
--do_lower_case \
--sequence_length 240 \
--batch_size BATCH_SIZE

Then evaluate the model:
python dense_retriever.py \
--encoder_model_type hf_bert \
--pretrained_model_cfg tau/spider \
--qa_file ./downloads/data/retriever/qas/trivia-test.csv\
--ctx_file ./downloads/data/wikipedia_split/psgs_w100.tsv \
--encoded_ctx_file "./wiki_embeddings/wikipedia_*.pkl" \
--output_dir ./tqa_results \
--n-docs 100 \
--num_threads 16 \
--batch_size 64 \
--sequence_length 240 \
--no_wandb

**Comment by oriram** [comment]
Hey @Gouzi3618,

This is my mistake, I forgot to add `--do_lower_case` to `dense_retrieval.py` in the README.
The reason why you didn't see a degradation in NQ is that in NQ the questions are already lower-cased.
Unfortunately, I tested this version of the repo mainly on NQ, so I didn't observe this bug.
I fixed this issue in the README.

Many thanks for pointing this issue!

**Comment by Gouzi3618** [comment]
Hi Ori,

Thank a lot!
