### ISSUE TITLE
Wikipedia dataset after being preprocessed

### ISSUE THREAD

**Issue by hieudx149** [oriram/spider#9]
Hi Ori Ram,
Can you public data after doing pre-processing (token and compute_recurring_spans) I try to run preprocess_corpus.py but I don't have many cpu cores, it takes me a lot of time to process.
Thanks

**Comment by oriram** [comment]
Hey @hieudx149,
Thanks for reaching out!

I believe that even with a few cores, it shouldn't take more than a few hours to run preprocessing.

Ori.
